# 端口号
server:
  servlet:
    context-path: /producer
  port: 8081

# 模块名称
module.name: spring-boot-producer

# 数据库url
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/bill?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
# 数据库用户名
  username: root
# 数据库密码
  password: root123
# 数据库驱动
  driver-class-name: com.mysql.cj.jdbc.Driver

# kafka配置
app.kafka.bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
kafka.topic: bill-topic-test

# 日志级别
logging.level: info

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml # mybatis-plus mapper xml 文件地址
  type-aliases-package: com.bill.entity # mybatis-plus type-aliases 文件地址
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰


